# Generated by Django 3.0.6 on 2020-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='was_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='receiver',
            field=models.ManyToManyField(blank=True, to='entities.Receiver'),
        ),
    ]
