# Generated by Django 3.0.6 on 2020-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
